# Generated by Django 6.0.2 on 2026-03-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_managers_remove_client_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Client"},
        ),
    ]
