# Generated by Django 6.0.2 on 2026-03-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="balance",
        ),
        migrations.AddField(
            model_name="transfer",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Сумма"),
        ),
    ]
