# Generated by Django 6.0.2 on 2026-03-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="number",
            field=models.CharField(
                max_length=16, unique=True, verbose_name="Номер карты"
            ),
        ),
    ]
